name = "memorykeeper-backend"  
compatibility_date = "2025-09-19"  
main = "src/index.ts"

# Bindings for D1, R2, and AI  
[[d1_databases]]  
binding = "DB"  
database_name = "memorykeeper-db"  
database_id = "your-production-d1-id"

[[r2_buckets]]  
binding = "PHOTOS_BUCKET"  
bucket_name = "memorykeeper-photos"

[[ai]]  
binding = "AI"

# Cron trigger for surprise enhancements or other scheduled jobs  
[[triggers]]  
crons = ["0 9 * * *"] # Runs at 9 AM UTC every day

[vars]  
# Production environment variables  
# These should be set via `wrangler secret put` for security  
# CLERK_JWKS_URI = "..."  
# CLERK_ISSUER = "..."

---
