name = "memorykeeper-backend"
compatibility_date = "2024-12-01"
main = "backend/src/index.ts"
compatibility_flags = ["nodejs_compat"]

# Bindings for D1, R2, and AI
[[d1_databases]]
binding = "DB"
database_name = "memorykeeper-db"
database_id = "77124aa9-fff7-4b3a-883e-bd909645e6c9"

[[r2_buckets]]
binding = "PHOTOS_BUCKET"
bucket_name = "memorykeeper-photos"

[ai]
binding = "AI"

# Cron trigger for processing background jobs
[triggers]
crons = ["* * * * *"] # Runs every minute to process jobs quickly in dev. Change for prod.

[vars]
# Production environment variables
# These should be set via `wrangler secret put` for security
# CLERK_JWKS_URI = "https://vast-osprey-17.clerk.accounts.dev/.well-known/jwks.json"
# CLERK_ISSUER = "https://vast-osprey-17.clerk.accounts.dev"