name = "memorykeeper-backend"
compatibility_date = "2025-06-17"
main = "backend/src/index.ts"

# Bindings for D1, R2, and AI
[[d1_databases]]
binding = "DB"
database_name = "memorykeeper-db"
database_id = "your-production-d1-id"

[[r2_buckets]]
binding = "PHOTOS_BUCKET"
bucket_name = "memorykeeper-photos"

[ai]
binding = "AI"

# Cron trigger for processing background jobs
[triggers]
# Use a more conservative schedule for production. Override per-environment if needed.
# Example: dev = every minute; prod = hourly.
crons = ["0 * * * *"]

[vars]
# Production environment variables
# These should be set via `wrangler secret put` for security
# CLERK_JWKS_URI = "..."
# CLERK_ISSUER = "..."