name = "memorykeeper-backend"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "memorykeeper"
database_id = "77124aa9-fff7-4b3a-883e-bd909645e6c9"

# Environment variables should be set via:
# 1. wrangler secret put CLERK_SECRET_KEY
# 2. wrangler secret put AUTH_SECRET
# 3. Or in .dev.vars for local development
